CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    profile VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);